language: julia
# addons:
#   apt_packages:
#     - gfortran
# before_install:
#   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
#         brew install gcc;
#     fi
jobs:
  include:
    - stage: test
      julia: 1.0
      os: osx
      env: STAGE=test
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - julia --check-bounds=yes -e 'using Pkg;
                    Pkg.add("SpecialFunctions");
                    Pkg.test("ForneyLab"; coverage=true)'
notifications:
  email: false